analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  errors:
    avoid_field_initializers_in_const_classes: error
    avoid_slow_async_io: error
    can_be_null_after_null_aware: error
    invalid_required_named_param: error
    invalid_required_positional_param: error
    invalid_use_of_protected_member: error
    invalid_use_of_visible_for_testing_member: error
    missing_required_param: error
    missing_return: error
    must_call_super: error
    prefer_constructors_over_static_methods: error
    unnecessary_cast: error
    null_aware_in_logical_operator: error
    always_declare_return_types: error
    always_put_required_named_parameters_first: error
    avoid_js_rounded_ints: error
    control_flow_in_finally: error
    directives_ordering: error
    invariant_booleans: error
    literal_only_boolean_expressions: error
    prefer_int_literals: error
    prefer_const_constructors_in_immutables: error
    prefer_const_literals_to_create_immutables: error
    prefer_typing_uninitialized_variables: error
    sort_unnamed_constructors_first: error
    throw_in_finally: error
    use_setters_to_change_properties: error
    use_string_buffers: error
    use_to_and_as_if_applicable: error
    avoid_setters_without_getters: ignore
    avoid_function_literals_in_foreach_calls: ignore
    avoid_implementing_value_types: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_types_on_closure_parameters: ignore
    cascade_invocations: ignore
    omit_local_variable_types: ignore
    prefer_collection_literals: ignore
    prefer_final_fields: ignore
    prefer_final_in_for_each: ignore
    prefer_final_locals: ignore
    prefer_function_declarations_over_variables: ignore
    prefer_inlined_adds: ignore
    prefer_interpolation_to_compose_strings: ignore
    prefer_mixin: ignore
    prefer_single_quotes: ignore
    prefer_spread_collections: ignore
    prefer_void_to_null: ignore
    type_annotate_public_apis: ignore
    unawaited_futures: ignore
    unnecessary_await_in_return: ignore
    unnecessary_brace_in_string_interps: ignore
    unnecessary_getters_setters: ignore
    unnecessary_parenthesis: ignore
    use_function_type_syntax_for_parameters: ignore
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    - avoid_field_initializers_in_const_classes
    - avoid_slow_async_io
    - prefer_constructors_over_static_methods
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_js_rounded_ints
    - control_flow_in_finally
    - directives_ordering
    - invariant_booleans
    - literal_only_boolean_expressions
    - prefer_int_literals
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_typing_uninitialized_variables
    - sort_unnamed_constructors_first
    - throw_in_finally
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - avoid_setters_without_getters
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_positional_boolean_parameters
    - avoid_types_on_closure_parameters
    - cascade_invocations
    - omit_local_variable_types
    - prefer_collection_literals
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_function_declarations_over_variables
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_mixin
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_void_to_null
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_parenthesis
    - use_function_type_syntax_for_parameters