name: baseball_stat_tracker
version: 0.0.1
description: Baseball Stat Tracker

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  built_value: ^7.1.0
  over_react: ^4.1.0
  react: ^6.0.0
  redux: ">=3.0.0 <5.0.0"

dev_dependencies:
  build_runner: ^1.10.0
  build_test: ^1.2.1
  build_web_compilers: ^2.9.0
  built_value_generator: ^7.1.0
  dart_dev: ^3.6.1
  dart_style: ^1.3.6
  test: ^1.15.7